### ISSUE TITLE
Can't see bank top.

### ISSUE THREAD

**Issue by loganpenin1** [AshleyThew/Bank#1]
I upgraded my bank plugin recently and everything is fine except the top.

![image](https://user-images.githubusercontent.com/66191749/122805713-d29bf000-d29f-11eb-90e4-38e7bf01f6b1.png)

This is what I see when I do /bank top money
Same happens with /bank top exp

Thanks!

**Comment by Dablakbandit** [comment]
Enable them in the hiscores.yml

**Comment by loganpenin1** [comment]
Thanks! I'll try

**Comment by AshleyThew** [comment]
Closed due to time.
